services:
  # Frontend service
  frontend:
    build:
      context: frontend
    container_name: frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - react-express
    depends_on:
      - backend

  # Backend service
  backend:
    build:
      context: backend
    container_name: backend
    environment:
      MONGO_HOST: mongodb
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DATABASE: ${MONGO_DATABASE}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - 3001:3001
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - express-mongo
      - react-express
    depends_on:
      - mongodb

  # MongoDB service
  mongodb:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - express-mongo

# Networks
networks:
  express-mongo:
  react-express:

# Volumes
volumes:
  mongo_data:
